### RAG Pipelines- Data Ingestion to Vector Database Pipeline

In [1]:
import os
from langchain_community.document_loaders import DirectoryLoader, PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

C:\Users\Admin\AppData\Local\Temp\ipykernel_21192\1659607159.py:2: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import DirectoryLoader, PyPDFLoader
c:\Users\Admin\OneDrive\Desktop\PROJECTS\RAG\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
from pathlib import Path
from langchain_community.document_loaders import PyPDFLoader


def process_all_pdfs(pdf_directory):
    """Process all PDF files in a directory"""

    all_documents = []
    pdf_dir = Path(pdf_directory)

    # Find all PDF files recursively in the directory
    pdf_files = list(pdf_dir.glob("**/*.pdf"))

    print(f"Found {len(pdf_files)} PDF files to process.")

    for pdf_file in pdf_files:
        print(f"\nProcessing file: {pdf_file}")

        try:
            loader = PyPDFLoader(str(pdf_file))
            documents = loader.load()

            # Add source information to metadata
            for doc in documents:
                doc.metadata["source_file"] = pdf_file.name
                doc.metadata["file_type"] = "pdf"

            all_documents.extend(documents)

            print(f"Loaded {len(documents)} pages")

        except Exception as e:
            print(f"Error: {e}")

    print(f"\nTotal documents loaded: {len(all_documents)}")

    return all_documents

In [3]:
# Process all PDFs in the data directory
all_pdf_documents = process_all_pdfs("../data")

Found 7 PDF files to process.

Processing file: ..\data\pdf\A better way to teach children to read in India.pdf
Loaded 42 pages

Processing file: ..\data\pdf\Attention.pdf

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/GKSXYT+TimesNewRomanPS-BoldItalicMT', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 99, '/FontDescriptor': IndirectObject(28, 0, 2158779080592), '/LastChar': 116, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [444, 0, 444, 0, 0, 0, 278, 0, 0, 278, 0, 556, 500, 0, 0, 389, 389, 278]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/MCBCCI+SourceSansRoman-Regular', '/Encoding': IndirectObject(50, 0, 2158779080592), '/FirstChar': 1, '/FontDescriptor': IndirectObject(51, 0, 2158779080592), '/LastChar': 8, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [456, 544, 496, 495, 200, 292, 542, 347]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/MCBCCM+SourceSansRoman.613wght', '/Encoding': IndirectObject(54, 0, 2158779080592), '/FirstChar': 1, '/FontDescriptor': IndirectObject(55, 0, 2158779080592), '/LastChar': 1, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [200]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/MCBCCO+SourceSansRoman-Bold', '/Encoding': IndirectObject(58, 0, 2158779080592), '/FirstChar': 1, '/FontDescriptor': IndirectObject(59, 0, 2158779080592), '/LastChar': 7, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [568, 573, 573, 527, 383, 518, 443]}, but is not installed. Consider installing fontTools if you encounter encoding problems.

Loaded 44 pages

Processing file: ..\data\pdf\CNN.pdf
Loaded 28 pages

Processing file: ..\data\pdf\EC4102_MidTerm_Proposal.pdf
Loaded 5 pages

Processing file: ..\data\pdf\Mid_term_applied_econometrics_group_6.pdf
Loaded 5 pages

Processing file: ..\data\pdf\SadakVision — INDIS 2026.pdf
Loaded 16 pages

Processing file: ..\data\pdf\SV_IEEE.pdf
Loaded 8 pages

Total documents loaded: 148

In [4]:
all_pdf_documents

[Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 0, 'page_label': '1', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content="A Better Way to Teach Children to Read? \nEvidence from a Randomized Controlled Trial1 \n \n \n \n \nMay 2009 \n \nFang He \n(Columbia University) \n \nLeigh L. Linden2 \n(Columbia University, BREAD, and IZA) \n \nMargaret MacLeod \n(Columbia University and U.S. Department of State) \n \n \n \n \n \n \n \n \nAbstract: Using\xa0three\xa0randomized\xa0evaluations,\xa0we\xa0assess\xa0the\xa0relative\xa0efficacy\xa0of\xa0a\xa0literacy\xa0skills\xa0\ndevelopment\xa0program\xa0in\xa0Mumbai,\xa0India\xa0on\xa0children\xa0in\xa0three\xa0types\xa0of\xa0educational\xa0institutions:\xa0public\xa0\nschools,\xa0a\xa0stand‐along\xa0reading\xa0class,\xa0and\xa0pre‐schools.\xa0\xa0The\xa0new\xa0methods\xa0prove\xa0effective\xa0in\xa0all\xa0\npopulations\xa0and,\xa0on\xa0average,\xa0all\xa0implementation\xa0strategies\xa0yield\xa0gains\xa0of\xa0between\xa00.12\xa0and\xa00.70\xa0\nstandard\xa0deviations\xa0in\xa0performance\xa0on\xa0a\xa0basic\xa0literacy\xa0assessment.\xa0\xa0The\xa0program\xa0seems\xa0to\xa0be\xa0more\xa0\neffective\xa0as\xa0a\xa0supplement\xa0to\xa0existing\xa0instruction\xa0rather\xa0than\xa0as\xa0a\xa0primary\xa0means\xa0of\xa0instruction.\xa0\xa0We\xa0find,\xa0\nfor\xa0example,\xa0that\xa0when\xa0implemented\xa0in\xa0public\xa0schools,\xa0an\xa0out‐of‐school\xa0time\xa0version\xa0of\xa0the\xa0program\xa0\nsignificantly\xa0improves\xa0scores\xa0over\xa0an\xa0in‐school\xa0version\xa0of\xa0the\xa0program.\xa0\xa0Additionally,\xa0we\xa0find\xa0that\xa0\nprograms\xa0based\xa0in\xa0existing\xa0institutions\xa0(public\xa0and\xa0pre‐\xa0schools)\xa0provide\xa0much\xa0more\xa0robust\xa0gains\xa0in\xa0\nstudent\xa0performance\xa0than\xa0the\xa0stand\xa0alone\xa0classes.\xa0\xa0Finally,\xa0in\xa0one\xa0experiment,\xa0we\xa0are\xa0also\xa0able\xa0to\xa0\ndisaggregate\xa0the\xa0effect\xa0of\xa0the\xa0techniques\xa0by\xa0the\xa0reading\xa0ability\xa0of\xa0children's\xa0parents\xa0and\xa0find\xa0that\xa0while\xa0\nparents’\xa0skills\xa0are\xa0correlated\xa0with\xa0children's,\xa0the\xa0effects\xa0of\xa0the\xa0program\xa0are\xa0fairly\xa0uniform\xa0across\xa0all\xa0\nstudents.\xa0\nJEL:\xa0C93,\xa0I21,\xa0I28\xa0\nKey\xa0Words:\xa0Education,\xa0Randomized\xa0Controlled\xa0Trial,\xa0Early\xa0Literacy\n\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\n1 Projects of this magnitude require the contributions of a large number of people.  While it would be impossible to \nrecognize everyone who made a contribution to this project, we are particularly indebted to the efforts of Pratima \nBandekar, Rajashree Kabare, Vidya Tiware, and Nandit Bhatt.  Funding for this project was provided by the \nPratham Mumbai Educational Trust and ICICI Bank of India.  Finally, this project simply would not have happened \nwithout the guidance and support of Madhav Chavan and Rukmini Banerji . The views expressed in this paper are \nthose of the authors, and do not necessarily reflect those of the U.S. Department of State or the U.S. Government. \n2 Corresponding author.  Please direct all correspondence to leigh.linden@columbia.edu."),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 1, 'page_label': '2', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='I.  Introduction \n The Millennium Development Goals and the Education for All initiatives have placed \nstrong emphasis on the promotion of universal primary education.  However, enrolling children \nis only a first step in educating children in developing countries.  The quality of education also \nmatters.  As Hanushek and Woessmann (2007) document in their survey of the evidence, \neducation quality differs significantly across countries and is especially low in developing \ncountries.  Consequently, to close the gap between developed and developing countries, \nprograms to improve education quality are crucial.  Effective methods to teach reading skills are \nparticularly important.  Existing research strongly suggests that learning to read at an early age \nlays a strong foundation for future academic skill development (Scarborough, 2001), suggesting \nthat improvements in early reading programs could yield significant dividends. \nThis study tries to help answer this question by looking at a particular education program \nthat seeks to improve the quality of language instruction for early learners in the slum \ncommunities of Mumbai, India.  In this particular setting, the quality of language instruction is \ngenerally poor and the need to improve existing education models is critical, especially at an \nearly age.  The main purpose of the curriculum is to provide basic literacy training to pre- school \nchildren to lay a foundation for their matriculation to regular primary schools.  However, as we \nshow, the program also provides a useful intervention for early primary students because unlike \nthe current teaching practices that focus on rote memorization and repetition, the Shishuvachan \ncurriculum focuses on comprehension facilitated by teacher-student interaction centered around \nstorytelling and classroom games. \nThe purpose of this study is to assess the effectiveness of the Shishuvachan curriculum.  \nRecent studies have suggested that the efficacy of educational strategies may vary by educational \ninstitution and by type of child (Duflo, Dupas, and Kremer, 2008; He, Linden, and Macleod,'),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 2, 'page_label': '3', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='2008).  As a result, we conduct three separate experiments over three years designed to evaluate \nthe effects of the program on three different student populations in three different types of \ninstitutions: first-grade students in government schools, pre-school students in specially designed \ncommunity-based Shishuvachan classes, and existing pre-school classes.  In addition, for the \ngovernment school population, we test two variants of the program – one that integrates the \nprogram into the regular school day and one that operates outside of school hours as a \nsupplement. \nOverall, we find that the program is quite effective an improving students reading scores.  \nThe effectiveness of the program on students within the individual institutions varies from 0.26 \nstandard deviations to 0.7 standard deviations.  The program seems to be more effective with \nstudents in certain institutions, proving most effective in the pre-schools classes for which it was \noriginally designed.  In addition, the program is particularly effective for low performing \nstudents.  Additionally, the program seems to generate much more robust gains in student \nachievement when run as a complement to existing institutions rather than when run in a \nstandalone, dedicated community based class.  Finally, within schools, the out-of-school time \nmodel proves significantly more beneficial than the in-school model increasing test scores by \n0.24 standard deviations beyond the 0.26 standard deviation effect of the within school model.  \nThis suggests that the program is most effective as a complement to teachers’ existing techniques \nrather than as a pure substitute. \n In our experiment with the existing pre-schoo ls we also collect information on parents’ \nreading abilities.  As expected, students’ reading skills are tightly correlated with parents’ skills.  \nChildren of parents who have achieved the ability to read a paragraph completely score 0.36 \nstandard deviations higher on our reading assessment than those whose parents cannot read a'),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 3, 'page_label': '4', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='paragraph.  However, despite these initial differences in the study population, the teaching \nmethods seem to have similar effects on all students. \nThis study complements a recent push in economics for randomized evaluations of \neducation programs in developing countries (for a review see Kremer (2003) and for a discussion \non randomized evaluations in developing countries see Duflo, Glennerster, and Kremer (2007)).  \nAmong many others, this body of work includes studies that assess a monitoring program for \nteacher attendance (Duflo, Hanna, and Ryan, 2007), ability grouping (Duflo, Dupas, and Kremer, \n2008), textbooks (Glewwe, Kremer, and Moulin (2003), and teacher incentives (Muralidharan \nand Sundararaman, 2008).  Compared to this body of work, this study is most closely aligned \nwith Bannerjee, Duflo, Cole and Linden (2006) and He, Linden, MacLeod (2008) both of which \nassess changes in pedagogy.  The former focused on math skills and providing remedial support \nfor low performing children, and the latter assesses teaching strategies to deliver English \nlanguage instruction to primary school children via a variety of delivery mechanisms.   \n The remainder of the paper is organized as  follows.  Section 2 provides an overview on \nthe early childhood literacy literature and Section 3 provides a description of the Shishuvachan \nintervention.  Section 4 provides a description of the research design including the experimental \ndesign, data collected, and statistical models.  We describe the sample and assess the internal \nvalidity of the study in Section 5.  And Section 6 provides estimates of the effects of the \ninterventions.  Finally, we conclude in Section 7. \n \nII. Early Literacy'),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 4, 'page_label': '5', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='The importance of early reading abilities is well  established in the literature.  In a review \nof this research, Scarborough (2001) conducts a review of 61 research samples and shows a high \ncorrelation between kindergarten reading skills and later reading scores.  Other studies such as \nCunningham and Stanovich (1997) show that there are strong associations between first grade \nreading abilities and later reading skills as well as achievement in the 11th grade; Storch and \nWhitehust (2002) show that pre-literacy skills (e.g. knowing that writing goes from left to right \nand top to bottom on a page) is important for reading comprehension later on.  Overall, there is a \nwealth of evidence showing a strong persistence in reading abilities starting from a young age. \nEarly strong readers tend to become strong readers later on and children with early \nreading disabilities tend to have reading disabilities even later into their academic career.  In \nparticular, vocabulary development may play a uniquely important role.  Biemiller (2006) shows \nevidence that early vocabulary development may be important for reading comprehension later \non.  Despite this evidence, Biemiller and Slonim (2001) find that among preliterate children \nvocabularies can differ by several thousand root-meanings, a gap that may be difficult to close.  \nSo even though this literature has not demonstrated an experimentally validated causal \nrelationship between early and late reading ability, there is strong suggestive evidence of a causal \nlink between early and late reading.  To the extent that later reading ability is important, so too is \nearly reading. \nThis connection has strong implications for low-income children in particular.  Because \nlow-income children tend to have home and school environments less conducive to early reading \ndevelopment relative to those of higher income children, low-income children develop lower pre \nreading abilities which then have strong implications for later reading abilities.  Capizanno et al \n(2000).  Burchinal et al (2000) and Dickinson and Sprague (2001) show that the quality of early'),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 5, 'page_label': '6', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='childhood classrooms is important for disadvantaged children from infancy to the preschool \nyears as these classroom settings may affect vocabulary and early literacy development.  This \nresearch highlights the importance of targeting early reading development for lower-income \nstudents. \nGiven this problem, previous research also shows that early intervention can be effective \nat addressing early reading difficulties.  Vellutino and Scanlon (2001) conduct a detailed study in \nwhich poor readers were identified and then randomly subjected to early one-on-one tutoring to \naddress their reading weaknesses.  The intervention proved effective, implying that rather than \nbeing a genetic disposition, reading skills can be developed.  Even though one-on-one tutoring \nmay not be feasible in low-income communities in developing countries, research shows that \nearly intervention may be effective and important. \n \nIII. Background - The Pratham Shishuvachan Program \n This study evaluates the Pratham Shishuvachan preschool program.  Shishuvachan is a \nprogram conducted by the Pratham Mumbai Education Initiative, an educational NGO founded \nin 1994 in the slum communities of Mumbai.  Its motto is “every child in school and learning \nwell.”3  Over the years it has grown into a large organization with operations in 14 Indian states \nfunded by the ICICI Bank of India, local governments, a large collection of corporate sponsors \nand international organizations, and local citizens.  In addition to the Shishuvachan program, \nPratham implements programs to mainstream out-of-school children into schools, programs \n\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\n3 http://www.pratham.org/aboutus/aboutus.php'),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 6, 'page_label': '7', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='teaching English to children using interactive electronic instruction booklets, and a variety of \nother educational programs. \nThe Shishuvachan program was originally designed to supplement balwadi (daycare) \nprograms run by Pratham, the government school system, and other organizations.  The \nprogram’s main goal is to develop reading and comprehension skills among children aged four to \nfive in preparation for primary school matriculation.  It consists of two main components: the \nShishuvachan classes and the Bal vachanalaya (child library).  In the class, teachers use story \nbooks, flash cards for word and letter recognition, and barakhadi charts4 to instruct children.  \nThe program aims to help children cognitively attach meaning to words and encourages children \nto take in whole words and ideas rather than overwhelming them with an abstract alphabet chart.  \nThe instructors engage in seven different activities: pre-reading, story-telling, story-reading, \nword recognition, letter recognition, barakhadi chart, and unfamiliar text reading. \nThe curriculum is precisely scheduled with specific activities conducted at specified \nperiods in the program.  Supervisors meet instructors twice a week, and four zonal heads meet \nsupervisors once every ten days to ensure consistency in training and implementation.  Both the \nclass and child library are offered in the community and are accessible to all age-appropriate \nchildren.  By participating in these two program components, children are expected to be able to \nread and comprehend simple unfamiliar stories after six months.   \nIn practice, the Shishuvachan method may not have a uniform effect on students \nindependent of the population of students or the method of delivery. Rather, a treatment can \n\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\n4In Indian languages that use the Devanagri alphabet, each character designates a specific syllable. As an abugida \nscript, the characters consist of a root consonant letter modified by diacritics indicating the different vowels.  The \nchart is a standard illustration of the pattern of modifications made to each character to represent the universe of \nconsonant-vowel matches.  Learning this chart is the functional equivalent of learning the English alphabet.'),

### Text Splitting and making Chunks

In [5]:
def split_documents(documents, chunk_size = 1000, chunk_overlap = 200):
    """Split documents into smaller chunks"""

    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size = chunk_size,
        chunk_overlap = chunk_overlap,
        length_function = len,
        separators = ["\n\n", "\n", " ", ""]
    )

    split_docs = text_splitter.split_documents(documents)
    print(f"Split {len(documents)} documents into {len(split_docs)} chunks")

    #Show example of a chunk
    if split_docs:
        print(f"\nExample chunk:")
        print(f"Content: {split_docs[0].page_content[:200]}...")
        print(f"Metadata: {split_docs[0].metadata} ")
    return split_docs

In [6]:
chunks = split_documents(all_pdf_documents)

Split 148 documents into 440 chunks

Example chunk:
Content: A Better Way to Teach Children to Read?
Evidence from a Randomized Controlled Trial1




May 2009

Fang He
(Columbia University)

Leigh L. Linden2
(Columbia University, BREAD, and IZA)

...
Metadata: {'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 0, 'page_label': '1', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}

### Embedding and Vector Store DB

In [7]:
import numpy as np
from sentence_transformers import SentenceTransformer
import chromadb
from chromadb.config import Settings
import uuid
from typing import List, Dict, Any, Tuple
from sklearn.metrics.pairwise import cosine_similarity

In [8]:
class EmbeddingManager:
    """Handles document embedding generation using SentenceTransformer."""

    def __init__(
        self,
        model_name: str = "all-MiniLM-L6-v2",
    ):
        """Initialize the EmbeddingManager."""
        self.model_name = model_name
        self.model = None
        self._load_model()

    def _load_model(self) -> None:
        """Load the SentenceTransformer model."""
        try:
            print(f"Loading embedding model: {self.model_name}")
            self.model = SentenceTransformer(self.model_name)
            print(
                f"Model loaded successfully: {self.model_name}. "
                f"Embedding dimension: "
                f"{self.model.get_sentence_embedding_dimension()}"
            )
        except Exception as e:
            print(f"Error loading embedding model: {e}")
            raise

    def generate_embeddings(self, texts: List[str]) -> np.ndarray:
        """Generate embeddings for a list of texts."""
        if self.model is None:
            raise ValueError("Model not loaded")

        print(f"Generating embeddings for {len(texts)} texts...")

        embeddings = self.model.encode(
            texts,
            show_progress_bar=True,
            convert_to_numpy=True,
        )

        print(f"Generated embeddings with shape: {embeddings.shape}")
        return embeddings

In [9]:
# initialize the embedding manager

embedding_manager = EmbeddingManager()
embedding_manager

Loading embedding model: all-MiniLM-L6-v2

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2607.44it/s]

Model loaded successfully: all-MiniLM-L6-v2. Embedding dimension: 384

C:\Users\Admin\AppData\Local\Temp\ipykernel_21192\3387099033.py:21: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  f"{self.model.get_sentence_embedding_dimension()}"

### VectorStore

In [10]:
import hashlib


class VectorStore:
    """Handles storage of document embeddings using ChromaDB."""

    def __init__(
        self,
        collection_name: str = "pdf_documents",
        persistent_directory: str = "../data/vector_store"
    ):
        """
        Initialize the VectorStore.

        Args:
            collection_name (str): Name of the ChromaDB collection.
            persistent_directory (str): Directory where the vector
                store will be persisted.
        """

        self.collection_name = collection_name
        self.persistent_directory = persistent_directory

        self.client = None
        self.collection = None

        self._initialize_store()

    def _initialize_store(self) -> None:
        """Initialize the persistent ChromaDB vector store."""

        try:
            # Create the directory if it doesn't exist
            os.makedirs(
                self.persistent_directory,
                exist_ok=True
            )

            # Create persistent ChromaDB client
            self.client = chromadb.PersistentClient(
                path=self.persistent_directory
            )

            # Get existing collection or create a new one
            self.collection = self.client.get_or_create_collection(
                name=self.collection_name,
                metadata={
                    "description": "PDF document embeddings for RAG"
                }
            )

            print(
                f"Vector store initialized. "
                f"Collection: {self.collection_name}"
            )

            print(
                f"Existing documents in collection: "
                f"{self.collection.count()}"
            )

        except Exception as e:
            print(f"Error initializing vector store: {e}")
            raise

    def reset_collection(self) -> None:
        """Delete the collection and re-create it empty."""
        try:
            self.client.delete_collection(name=self.collection_name)
        except Exception:
            pass  # collection didn't exist yet

        self.collection = self.client.get_or_create_collection(
            name=self.collection_name,
            metadata={
                "description": "PDF document embeddings for RAG"
            }
        )
        print(f"Collection '{self.collection_name}' reset (now empty).")

    @staticmethod
    def _make_id(doc) -> str:
        """Deterministic ID: same source + page + text always gives the same ID."""
        key = (
            f"{doc.metadata.get('source_file', doc.metadata.get('source', ''))}"
            f"|{doc.metadata.get('page', '')}"
            f"|{doc.page_content}"
        )
        return "doc_" + hashlib.sha256(key.encode("utf-8")).hexdigest()[:32]

    def add_documents(
        self,
        documents: List[Any],
        embeddings: np.ndarray,
        replace: bool = True
    ) -> None:
        """
        Add documents and their embeddings to the vector store.

        Args:
            documents: List of LangChain Document objects.
            embeddings: Corresponding embeddings for the documents.
            replace: If True (default), wipe the collection first so the
                stored data exactly matches the documents passed in.
                Re-running ingestion never creates duplicates.
        """

        if not documents or embeddings.size == 0:
            raise ValueError(
                "Documents and embeddings cannot be empty"
            )

        if len(documents) != len(embeddings):
            raise ValueError(
                "Number of documents and embeddings must match"
            )

        print(
            f"Adding {len(documents)} documents "
            f"to the vector store..."
        )

        if replace:
            self.reset_collection()

        # Prepare data for ChromaDB
        ids = []
        metadatas = []
        documents_text = []
        embeddings_list = []

        for i, (doc, embedding) in enumerate(
            zip(documents, embeddings)
        ):

            # Deterministic document ID (content hash)
            doc_id = self._make_id(doc)
            ids.append(doc_id)

            # Prepare metadata
            metadata = dict(doc.metadata)

            metadata["doc_index"] = i
            metadata["content_length"] = len(
                doc.page_content
            )

            metadatas.append(metadata)

            # Store original document text
            documents_text.append(
                doc.page_content
            )

            # Convert NumPy array to Python list
            embeddings_list.append(
                embedding.tolist()
            )

        # Add everything to ChromaDB
        try:
            self.collection.upsert(
                ids=ids,
                embeddings=embeddings_list,
                metadatas=metadatas,
                documents=documents_text
            )

            print(
                f"Successfully added {len(documents)} "
                f"documents to the vector store."
            )

            print(
                f"Total documents in collection after addition: "
                f"{self.collection.count()}"
            )

        except Exception as e:
            print(
                f"Error adding documents to vector store: {e}"
            )
            raise

In [11]:
vector_store = VectorStore()
vector_store

Vector store initialized. Collection: pdf_documents
Existing documents in collection: 440

In [12]:
chunks

[Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 0, 'page_label': '1', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='A Better Way to Teach Children to Read? \nEvidence from a Randomized Controlled Trial1 \n \n \n \n \nMay 2009 \n \nFang He \n(Columbia University) \n \nLeigh L. Linden2 \n(Columbia University, BREAD, and IZA) \n \nMargaret MacLeod \n(Columbia University and U.S. Department of State) \n \n \n \n \n \n \n \n \nAbstract: Using\xa0three\xa0randomized\xa0evaluations,\xa0we\xa0assess\xa0the\xa0relative\xa0efficacy\xa0of\xa0a\xa0literacy\xa0skills\xa0\ndevelopment\xa0program\xa0in\xa0Mumbai,\xa0India\xa0on\xa0children\xa0in\xa0three\xa0types\xa0of\xa0educational\xa0institutions:\xa0public\xa0\nschools,\xa0a\xa0stand‐along\xa0reading\xa0class,\xa0and\xa0pre‐schools.\xa0\xa0The\xa0new\xa0methods\xa0prove\xa0effective\xa0in\xa0all\xa0\npopulations\xa0and,\xa0on\xa0average,\xa0all\xa0implementation\xa0strategies\xa0yield\xa0gains\xa0of\xa0between\xa00.12\xa0and\xa00.70\xa0\nstandard\xa0deviations\xa0in\xa0performance\xa0on\xa0a\xa0basic\xa0literacy\xa0assessment.\xa0\xa0The\xa0program\xa0seems\xa0to\xa0be\xa0more\xa0\neffective\xa0as\xa0a\xa0supplement\xa0to\xa0existing\xa0instruction\xa0rather\xa0than\xa0as\xa0a\xa0primary\xa0means\xa0of\xa0instruction.\xa0\xa0We\xa0find,\xa0\nfor\xa0example,\xa0that\xa0when\xa0implemented\xa0in\xa0public\xa0schools,\xa0an\xa0out‐of‐school\xa0time\xa0version\xa0of\xa0the\xa0program'),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 0, 'page_label': '1', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content="for\xa0example,\xa0that\xa0when\xa0implemented\xa0in\xa0public\xa0schools,\xa0an\xa0out‐of‐school\xa0time\xa0version\xa0of\xa0the\xa0program\xa0\nsignificantly\xa0improves\xa0scores\xa0over\xa0an\xa0in‐school\xa0version\xa0of\xa0the\xa0program.\xa0\xa0Additionally,\xa0we\xa0find\xa0that\xa0\nprograms\xa0based\xa0in\xa0existing\xa0institutions\xa0(public\xa0and\xa0pre‐\xa0schools)\xa0provide\xa0much\xa0more\xa0robust\xa0gains\xa0in\xa0\nstudent\xa0performance\xa0than\xa0the\xa0stand\xa0alone\xa0classes.\xa0\xa0Finally,\xa0in\xa0one\xa0experiment,\xa0we\xa0are\xa0also\xa0able\xa0to\xa0\ndisaggregate\xa0the\xa0effect\xa0of\xa0the\xa0techniques\xa0by\xa0the\xa0reading\xa0ability\xa0of\xa0children's\xa0parents\xa0and\xa0find\xa0that\xa0while\xa0\nparents’\xa0skills\xa0are\xa0correlated\xa0with\xa0children's,\xa0the\xa0effects\xa0of\xa0the\xa0program\xa0are\xa0fairly\xa0uniform\xa0across\xa0all\xa0\nstudents.\xa0\nJEL:\xa0C93,\xa0I21,\xa0I28\xa0\nKey\xa0Words:\xa0Education,\xa0Randomized\xa0Controlled\xa0Trial,\xa0Early\xa0Literacy\n\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\n1 Projects of this magnitude require the contributions of a large number of people.  While it would be impossible to"),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 0, 'page_label': '1', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='1 Projects of this magnitude require the contributions of a large number of people.  While it would be impossible to \nrecognize everyone who made a contribution to this project, we are particularly indebted to the efforts of Pratima \nBandekar, Rajashree Kabare, Vidya Tiware, and Nandit Bhatt.  Funding for this project was provided by the \nPratham Mumbai Educational Trust and ICICI Bank of India.  Finally, this project simply would not have happened \nwithout the guidance and support of Madhav Chavan and Rukmini Banerji . The views expressed in this paper are \nthose of the authors, and do not necessarily reflect those of the U.S. Department of State or the U.S. Government. \n2 Corresponding author.  Please direct all correspondence to leigh.linden@columbia.edu.'),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 1, 'page_label': '2', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='I.  Introduction \n The Millennium Development Goals and the Education for All initiatives have placed \nstrong emphasis on the promotion of universal primary education.  However, enrolling children \nis only a first step in educating children in developing countries.  The quality of education also \nmatters.  As Hanushek and Woessmann (2007) document in their survey of the evidence, \neducation quality differs significantly across countries and is especially low in developing \ncountries.  Consequently, to close the gap between developed and developing countries, \nprograms to improve education quality are crucial.  Effective methods to teach reading skills are \nparticularly important.  Existing research strongly suggests that learning to read at an early age \nlays a strong foundation for future academic skill development (Scarborough, 2001), suggesting \nthat improvements in early reading programs could yield significant dividends.'),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 1, 'page_label': '2', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='lays a strong foundation for future academic skill development (Scarborough, 2001), suggesting \nthat improvements in early reading programs could yield significant dividends. \nThis study tries to help answer this question by looking at a particular education program \nthat seeks to improve the quality of language instruction for early learners in the slum \ncommunities of Mumbai, India.  In this particular setting, the quality of language instruction is \ngenerally poor and the need to improve existing education models is critical, especially at an \nearly age.  The main purpose of the curriculum is to provide basic literacy training to pre- school \nchildren to lay a foundation for their matriculation to regular primary schools.  However, as we \nshow, the program also provides a useful intervention for early primary students because unlike \nthe current teaching practices that focus on rote memorization and repetition, the Shishuvachan'),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 1, 'page_label': '2', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='show, the program also provides a useful intervention for early primary students because unlike \nthe current teaching practices that focus on rote memorization and repetition, the Shishuvachan \ncurriculum focuses on comprehension facilitated by teacher-student interaction centered around \nstorytelling and classroom games. \nThe purpose of this study is to assess the effectiveness of the Shishuvachan curriculum.  \nRecent studies have suggested that the efficacy of educational strategies may vary by educational \ninstitution and by type of child (Duflo, Dupas, and Kremer, 2008; He, Linden, and Macleod,'),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 2, 'page_label': '3', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='2008).  As a result, we conduct three separate experiments over three years designed to evaluate \nthe effects of the program on three different student populations in three different types of \ninstitutions: first-grade students in government schools, pre-school students in specially designed \ncommunity-based Shishuvachan classes, and existing pre-school classes.  In addition, for the \ngovernment school population, we test two variants of the program – one that integrates the \nprogram into the regular school day and one that operates outside of school hours as a \nsupplement. \nOverall, we find that the program is quite effective an improving students reading scores.  \nThe effectiveness of the program on students within the individual institutions varies from 0.26 \nstandard deviations to 0.7 standard deviations.  The program seems to be more effective with \nstudents in certain institutions, proving most effective in the pre-schools classes for which it was'),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 2, 'page_label': '3', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='standard deviations to 0.7 standard deviations.  The program seems to be more effective with \nstudents in certain institutions, proving most effective in the pre-schools classes for which it was \noriginally designed.  In addition, the program is particularly effective for low performing \nstudents.  Additionally, the program seems to generate much more robust gains in student \nachievement when run as a complement to existing institutions rather than when run in a \nstandalone, dedicated community based class.  Finally, within schools, the out-of-school time \nmodel proves significantly more beneficial than the in-school model increasing test scores by \n0.24 standard deviations beyond the 0.26 standard deviation effect of the within school model.  \nThis suggests that the program is most effective as a complement to teachers’ existing techniques \nrather than as a pure substitute. \n In our experiment with the existing pre-schoo ls we also collect information on parents’'),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 2, 'page_label': '3', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='rather than as a pure substitute. \n In our experiment with the existing pre-schoo ls we also collect information on parents’ \nreading abilities.  As expected, students’ reading skills are tightly correlated with parents’ skills.  \nChildren of parents who have achieved the ability to read a paragraph completely score 0.36 \nstandard deviations higher on our reading assessment than those whose parents cannot read a'),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 3, 'page_label': '4', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='paragraph.  However, despite these initial differences in the study population, the teaching \nmethods seem to have similar effects on all students. \nThis study complements a recent push in economics for randomized evaluations of \neducation programs in developing countries (for a review see Kremer (2003) and for a discussion \non randomized evaluations in developing countries see Duflo, Glennerster, and Kremer (2007)).  \nAmong many others, this body of work includes studies that assess a monitoring program for \nteacher attendance (Duflo, Hanna, and Ryan, 2007), ability grouping (Duflo, Dupas, and Kremer, \n2008), textbooks (Glewwe, Kremer, and Moulin (2003), and teacher incentives (Muralidharan \nand Sundararaman, 2008).  Compared to this body of work, this study is most closely aligned \nwith Bannerjee, Duflo, Cole and Linden (2006) and He, Linden, MacLeod (2008) both of which \nassess changes in pedagogy.  The former focused on math skills and providing remedial support'),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 3, 'page_label': '4', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='with Bannerjee, Duflo, Cole and Linden (2006) and He, Linden, MacLeod (2008) both of which \nassess changes in pedagogy.  The former focused on math skills and providing remedial support \nfor low performing children, and the latter assesses teaching strategies to deliver English \nlanguage instruction to primary school children via a variety of delivery mechanisms.   \n The remainder of the paper is organized as  follows.  Section 2 provides an overview on \nthe early childhood literacy literature and Section 3 provides a description of the Shishuvachan \nintervention.  Section 4 provides a description of the research design including the experimental \ndesign, data collected, and statistical models.  We describe the sample and assess the internal \nvalidity of the study in Section 5.  And Section 6 provides estimates of the effects of the \ninterventions.  Finally, we conclude in Section 7. \n \nII. Early Literacy'),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 4, 'page_label': '5', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='The importance of early reading abilities is well  established in the literature.  In a review \nof this research, Scarborough (2001) conducts a review of 61 research samples and shows a high \ncorrelation between kindergarten reading skills and later reading scores.  Other studies such as \nCunningham and Stanovich (1997) show that there are strong associations between first grade \nreading abilities and later reading skills as well as achievement in the 11th grade; Storch and \nWhitehust (2002) show that pre-literacy skills (e.g. knowing that writing goes from left to right \nand top to bottom on a page) is important for reading comprehension later on.  Overall, there is a \nwealth of evidence showing a strong persistence in reading abilities starting from a young age. \nEarly strong readers tend to become strong readers later on and children with early \nreading disabilities tend to have reading disabilities even later into their academic career.  In'),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 4, 'page_label': '5', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='Early strong readers tend to become strong readers later on and children with early \nreading disabilities tend to have reading disabilities even later into their academic career.  In \nparticular, vocabulary development may play a uniquely important role.  Biemiller (2006) shows \nevidence that early vocabulary development may be important for reading comprehension later \non.  Despite this evidence, Biemiller and Slonim (2001) find that among preliterate children \nvocabularies can differ by several thousand root-meanings, a gap that may be difficult to close.  \nSo even though this literature has not demonstrated an experimentally validated causal \nrelationship between early and late reading ability, there is strong suggestive evidence of a causal \nlink between early and late reading.  To the extent that later reading ability is important, so too is \nearly reading. \nThis connection has strong implications for low-income children in particular.  Because'),
 Document(metadata={'producer': 'Acrobat Distiller 9.2.0 (Windows)', 'creator': 'PScript5.dll Version 5.2.2', 'creationdate': '2010-01-19T12:19:10-05:00', 'author': 'Leigh', 'moddate': '2010-01-19T12:36:55-05:00', 'title': 'Microsoft Word - Shishu Working Paper 2009-06-1', 'source': '..\\data\\pdf\\A better way to teach children to read in India.pdf', 'total_pages': 42, 'page': 4, 'page_label': '5', 'source_file': 'A better way to teach children to read in India.pdf', 'file_type': 'pdf'}, page_content='early reading. \nThis connection has strong implications for low-income children in particular.  Because \nlow-income children tend to have home and school environments less conducive to early reading \ndevelopment relative to those of higher income children, low-income children develop lower pre \nreading abilities which then have strong implications for later reading abilities.  Capizanno et al \n(2000).  Burchinal et al (2000) and Dickinson and Sprague (2001) show that the quality of early'),

In [13]:
### Convert the text to embeddings
texts = [doc.page_content for doc in chunks]

### Generate embeddings for the document chunks
embeddings = embedding_manager.generate_embeddings(texts)

###Store in the vector store
vector_store.add_documents(chunks, embeddings)

Generating embeddings for 440 texts...

Batches: 100%|██████████| 14/14 [00:24<00:00,  1.73s/it]

Generated embeddings with shape: (440, 384)
Adding 440 documents to the vector store...
Collection 'pdf_documents' reset (now empty).
Successfully added 440 documents to the vector store.
Total documents in collection after addition: 440

### RAG Retriever from VectorStore (use query to retrieve relevant documents)

In [14]:
class RAGRetriever:
    """Handles query-based retrieval from the vector store."""

    def __init__(
        self,
        vector_store: VectorStore,
        embedding_manager: EmbeddingManager
    ):
        """
        Initialize the retriever.

        Args:
            vector_store: Vector store containing document embeddings.
            embedding_manager: Manager for generating query embeddings.
        """

        self.vector_store = vector_store
        self.embedding_manager = embedding_manager

    def retrieve(
        self,
        query: str,
        top_k: int = 5,
        score_threshold: float = 0.0
    ) -> List[Dict[str, Any]]:
        """
        Retrieve relevant documents for a query.

        Args:
            query: The search query.
            top_k: Number of top results to return.
            score_threshold: Minimum similarity score required.

        Returns:
            List of dictionaries containing:
            - document ID
            - document content
            - metadata
            - similarity score
            - distance
            - rank
        """

        print(f"Retrieving documents for query: '{query}'")
        print(
            f"Top K: {top_k}, "
            f"Score threshold: {score_threshold}"
        )

        # --------------------------------------------------
        # 1. Generate embedding for the user's query
        # --------------------------------------------------

        query_embedding = (
            self.embedding_manager
            .generate_embeddings([query])[0]
        )

        # --------------------------------------------------
        # 2. Search the vector store
        # --------------------------------------------------

        try:

            results = self.vector_store.collection.query(
                query_embeddings=[
                    query_embedding.tolist()
                ],
                n_results=top_k
            )

            # --------------------------------------------------
            # 3. Process the search results
            # --------------------------------------------------

            retrieved_docs = []

            if results["documents"] and results["documents"][0]:

                documents = results["documents"][0]
                metadatas = results["metadatas"][0]
                distances = results["distances"][0]
                ids = results["ids"][0]

                # --------------------------------------------------
                # 4. Process each retrieved document
                # --------------------------------------------------

                for i, (
                    doc_id,
                    document,
                    metadata,
                    distance
                ) in enumerate(
                    zip(
                        ids,
                        documents,
                        metadatas,
                        distances
                    )
                ):

                    # ChromaDB returns cosine distance.
                    # Convert distance to similarity score.
                    similarity_score = 1 - distance

                    # --------------------------------------------------
                    # 5. Apply similarity threshold
                    # --------------------------------------------------

                    if similarity_score >= score_threshold:

                        retrieved_docs.append({
                            "id": doc_id,
                            "content": document,
                            "metadata": metadata,
                            "similarity_score": similarity_score,
                            "distance": distance,
                            "rank": i + 1
                        })

                print(
                    f"Retrieved {len(retrieved_docs)} "
                    f"documents (after filtering)"
                )

            else:

                print("No documents found")

            return retrieved_docs

        except Exception as e:

            print(f"Error during retrieval: {e}")

            return []

In [15]:
rag_retriever = RAGRetriever(vector_store, embedding_manager)
rag_retriever

In [16]:
rag_retriever.retrieve("What is sadak vision?")

Retrieving documents for query: 'What is sadak vision?'
Top K: 5, Score threshold: 0.0
Generating embeddings for 1 texts...

Batches: 100%|██████████| 1/1 [00:00<00:00, 43.84it/s]

Generated embeddings with shape: (1, 384)
Retrieved 3 documents (after filtering)

[{'id': 'doc_d9a71857941dca31d2541cfcccbfe001',
  'content': 'Vision-level accuracy, 89% less compute , plus severity\nSensor only Vision only Fusion (SadakVision)\n0.48\n0.782 0.782 0.823 0.787 0.787\n0.606\n0.785 0.785\nPrecision Recall F1\nSame F1\nas vision-only, by design: the sensor decides what\nthe camera looks at, vision gives the verdict.\n 89%\nframes sent to the detector: 4,620 vs 43,200\nan hour.\n+ Severity\nlow / medium / high from the sensor trace.\nChecked so far on 62 human-labelled events.\nSadakVision · INDIS 2026 10',
  'metadata': {'total_pages': 16,
   'content_length': 464,
   'doc_index': 400,
   'page_label': '10',
   'source': '..\\data\\pdf\\SadakVision — INDIS 2026.pdf',
   'creationdate': '',
   'page': 9,
   'creator': 'PyPDF',
   'producer': 'appifact kit',
   'file_type': 'pdf',
   'title': 'SadakVision   INDIS 2026',
   'source_file': 'SadakVision — INDIS 2026.pdf'},
  'similarity_score': 0.09582984447479248,
  'distance': 0.9041701555252075,
  'rank': 1},
 {'id': 'doc_c4b3abd6c017bb384dc1eb6aaf936994',
  'content': 'SADAKVISION\nSensor–vision fusion for scalable smartphone\nroad monitoring\nINDIS 2026\nAbhijeet Shashwat · Avishkar Rawal · Devyansh Agarwal · Raghav Sarna · Srikant Srinivasan · Shreyansh Singh\nDixon IoT Lab, Plaksha University, Mohali · Transportation & Mobility Design · IIT Guwahati',
  'metadata': {'producer': 'appifact kit',
   'creator': 'PyPDF',
   'title': 'SadakVision   INDIS 2026',
   'doc_index': 391,
   'creationdate': '',
   'total_pages': 16,
   'page': 0,
   'page_label': '1',
   'file_type': 'pdf',
   'source': '..\\data\\pdf\\SadakVision — INDIS 2026.pdf',
   'source_file': 'SadakVision — INDIS 2026.pdf',
   'content_length': 283},
  'similarity_score': 0.029503583908081055,
  'distance': 0.970496416091919,
  'rank': 2},
 {'id': 'doc_3a99327bbb9b1410badb81ca229f7b90',
  'content': 'Vision F1:\n0.628\nNo\nVarona et al. [5] Sensor 93% No\nSadakVision\n(ours)\nFusion 63.6% Yes (3-level)\nD. Comparison with Existing Methods\nTable VI positions our results against related work. Direct\ncomparison is imperfect because datasets differ, but the table\ncontextualizes our numbers.\nTABLE VI\nCOMPARISON WITH RELATED APPROACHES\nMethod Modality mAP /\nAcc.\nSeverity?\nRamesh et al. [3]\nYOLOv5\nVision 87.5% No\nRamesh et al. [3]\nLSTM\nSensor 94% Depth est.\nDoshi &\nYilmaz [10]\nVision F1:\n0.628\nNo\nVarona et al. [5] Sensor 93% No\nSadakVision\n(ours)\nFusion [TO FILL]% Yes (3-level)\nE. Deployment and Dashboard\nThe system is deployed and accessible at\nsadakvision.com. The web dashboard displays detected\npotholes on an interactive map with severity-coded markers.\n[TO FILL: Add 1–2 sentences on any additional dashboard\nfeatures, e.g., filtering by date, AQI overlay, etc.]\nV. CONCLUSION ANDFUTUREWORK\nWe presented SadakVision, a smartphone-based road mon-',
  'metadata': {'creationdate': '2026-04-15T16:06:52+00:00',
   'creator': 'LaTeX with hyperref',
   'source': '..\\data\\pdf\\SV_IEEE.pdf',
   'subject': '',
   'page': 6,
   'title': '',
   'content_length': 949,
   'moddate': '2026-04-15T16:06:52+00:00',
   'page_label': '7',
   'total_pages': 8,
   'doc_index': 433,
   'trapped': '/False',
   'producer': 'pdfTeX-1.40.27',
   'author': '',
   'file_type': 'pdf',
   'keywords': '',
   'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.27 (TeX Live 2025) kpathsea version 6.4.1',
   'source_file': 'SV_IEEE.pdf'},
  'similarity_score': 0.016919970512390137,
  'distance': 0.9830800294876099,
  'rank': 3}]

### Intergration VectorDB Context pipeline with LLM output

In [17]:
### Simple RAG pipeline with Groq LLM

from langchain_groq import ChatGroq
import os
from dotenv import load_dotenv


# Load environment variables from .env
load_dotenv()


# Get Groq API key
groq_api_key = os.getenv("GROQ_API_KEY")

if not groq_api_key:
    raise ValueError("GROQ_API_KEY not found in .env file")


# Initialize the Groq LLM
llm = ChatGroq(
    groq_api_key=groq_api_key,
    # model_name="gemma2-9b-it",
    model_name = "openai/gpt-oss-20b",
    temperature=0.1,
    max_tokens=1024
)


# Simple RAG pipeline:
# Retrieve relevant context + generate answer
def rag_simple(query, retriever, llm, top_k=3):

    # 1. Retrieve relevant documents
    results = retriever.retrieve(
        query,
        top_k=top_k
    )

    # 2. Combine retrieved document chunks into one context
    context = "\n\n".join(
        doc["content"]
        for doc in results
    ) if results else ""

    # 3. Handle case where no relevant documents are found
    if not context:
        print("No relevant documents found for the query.")
        return "No relevant documents found."

    # 4. Create the prompt for the LLM
    prompt = f"""
Use the following context to answer the question concisely.
Only use information from the provided context.

Context:
{context}

Question:
{query}

Answer:
"""

    # 5. Send the prompt to the Groq LLM
    response = llm.invoke(prompt)

    # 6. Return the generated answer
    return response.content

In [18]:
# Example usage
query = "What is the Attention Mechanism?"

answer = rag_simple(
    query=query,
    retriever=rag_retriever,
    llm=llm,
    top_k=3
)

print("\nFinal Answer:")
print(answer)

Retrieving documents for query: 'What is the Attention Mechanism?'
Top K: 3, Score threshold: 0.0
Generating embeddings for 1 texts...

Batches: 100%|██████████| 1/1 [00:00<00:00, 54.56it/s]

Generated embeddings with shape: (1, 384)
Retrieved 3 documents (after filtering)

Final Answer:
**Answer:**
An attention mechanism is a differentiable function that takes queries, keys, and values as input and produces an output that aggregates information from the values weighted by the similarity between queries and keys.

### Enhanced RAG Pipeline Features

In [19]:
# --- Enhanced RAG Pipeline Features ---

def rag_advanced(query, retriever, llm, top_k=5, min_score=0.2, return_context=False):
    """
    RAG pipeline with extra features:
    - Returns answer, sources, confidence score, and optionally full context.
    """
    results = retriever.retrieve(query, top_k=top_k, score_threshold=min_score)

    if not results:
        return {
            'answer': 'No relevant context found.',
            'sources': [],
            'confidence': 0.0,
            'context': ''
        }

    # Prepare context and sources
    context = "\n\n".join([doc['content'] for doc in results])

    sources = [{
        'source': doc['metadata'].get(
            'source_file',
            doc['metadata'].get('source', 'unknown')
        ),
        'page': doc['metadata'].get('page', 'unknown'),
        'score': doc['similarity_score'],
        'preview': doc['content'][:120] + '...'
    } for doc in results]

    confidence = max(
        [doc['similarity_score'] for doc in results]
    )

    # Generate answer
    prompt = f"""Use the following context to answer the question concisely.
Context:
{context}

Question: {query}

Answer:"""

    response = llm.invoke(
        [prompt.format(context=context, query=query)]
    )

    output = {
        'answer': response.content,
        'sources': sources,
        'confidence': confidence
    }

    if return_context:
        output['context'] = context

    return output

In [20]:
# Example usage of the advanced RAG pipeline
result = rag_advanced(
    query="what is better way to teach attention mechanism  ?",
    retriever=rag_retriever,
    llm=llm,
    top_k=5,
    min_score=0.005,
    return_context=True
)
print("Answer:", result['answer'])
print("Sources:", result['sources'])
print("Confidence Score:", result['confidence'])
print("Context Preview:", result['context'][:300])

Retrieving documents for query: 'what is better way to teach attention mechanism  ?'
Top K: 5, Score threshold: 0.005
Generating embeddings for 1 texts...

Batches: 100%|██████████| 1/1 [00:00<00:00, 57.06it/s]

Generated embeddings with shape: (1, 384)
Retrieved 3 documents (after filtering)

Answer: **A concise recipe for “teaching” attention:**

1. **Pre‑train on a large, diverse corpus** – let the model discover useful patterns (positional, syntactic, broadcast) automatically.
2. **Add explicit supervision** – when possible, provide attention‑target signals (e.g., alignments, parse trees, or saliency maps) and add a small attention‑loss term to the training objective.
3. **Use a curriculum** – start with simple, local patterns (next/previous tokens, local spatial windows) and gradually introduce global, multi‑head patterns.
4. **Combine channel‑ and spatial‑attention modules** – train them jointly so the network learns to aggregate information both across feature maps and across positions.
5. **Fine‑tune on the target task** – keep the learned attention weights as a prior and let the model adapt them to the specific domain.

This blend of unsupervised pre‑training, targeted supervision, curriculum learning, and joint channel/spatial attention yields the most effective, interpretable attention mechanisms.
Sources: [{'source': 'Attention.pdf', 'page': 37, 'score': 0.09066545963287354, 'preview': 'in this monograph establish the theoretical basis for understanding these mechanisms, while highlighting\nopen questions ...'}, {'source': 'CNN.pdf', 'page': 22, 'score': 0.08530634641647339, 'preview': 'in a sequential fashion.\n• Channel attention maps assist in determining\nwhere to focus one’s attention;\n• Spatial attent...'}, {'source': 'Attention.pdf', 'page': 19, 'score': 0.06306922435760498, 'preview': '18 CHAPTER 3. SELF-ATTENTION MECHANISMS\nExample 3.2(Positional Patterns).Some attention heads learn to attend to specifi...'}]
Confidence Score: 0.09066545963287354
Context Preview: in this monograph establish the theoretical basis for understanding these mechanisms, while highlighting
open questions and challenges. As research addresses efficiency, theoretical understanding, interpretability,
and domain-specific applications, attention-based architectures will continue evolvin

In [21]:
# --- Advanced RAG Pipeline: Streaming, Citations, History, Summarization ---

from typing import List, Dict, Any
import time


class AdvancedRAGPipeline:

    def __init__(self, retriever, llm):
        self.retriever = retriever
        self.llm = llm
        self.history = []  # Store query history

    def query(
        self,
        question: str,
        top_k: int = 5,
        min_score: float = 0.2,
        stream: bool = False,
        summarize: bool = False
    ) -> Dict[str, Any]:

        # Retrieve relevant documents
        results = self.retriever.retrieve(
            question,
            top_k=top_k,
            score_threshold=min_score
        )

        if not results:
            answer = "No relevant context found."
            sources = []
            context = ""

        else:
            context = "\n\n".join(
                [doc["content"] for doc in results]
            )

            sources = [
                {
                    "source": doc["metadata"].get(
                        "source_file",
                        doc["metadata"].get("source", "unknown")
                    ),
                    "page": doc["metadata"].get(
                        "page",
                        "unknown"
                    ),
                    "score": doc["similarity_score"],
                    "preview": doc["content"][:120] + "..."
                }
                for doc in results
            ]

            # Streaming answer simulation
            prompt = f"""Use the following context to answer the question concisely.
Context:
{context}

Question: {question}

Answer:"""

            if stream:
                print("Streaming answer:")

                for i in range(0, len(prompt), 80):
                    print(
                        prompt[i:i + 80],
                        end="",
                        flush=True
                    )
                    time.sleep(0.05)

                print()

            response = self.llm.invoke(
                [prompt.format(
                    context=context,
                    question=question
                )]
            )

            answer = response.content

        # Add citations to answer
        citations = [
            f"[{i + 1}] {src['source']} (page {src['page']})"
            for i, src in enumerate(sources)
        ]

        answer_with_citations = (
            answer
            + "\n\nCitations:\n"
            + "\n".join(citations)
            if citations
            else answer
        )

        # Optionally summarize answer
        summary = None

        if summarize and answer:
            summary_prompt = (
                f"Summarize the following answer in 2 sentences:\n"
                f"{answer}"
            )

            summary_resp = self.llm.invoke(
                [summary_prompt]
            )

            summary = summary_resp.content

        # Store query history
        self.history.append({
            "question": question,
            "answer": answer,
            "sources": sources,
            "summary": summary
        })

        return {
            "question": question,
            "answer": answer_with_citations,
            "sources": sources,
            "summary": summary,
            "history": self.history
        }

In [22]:
# Example usage
adv_rag = AdvancedRAGPipeline(
    rag_retriever,
    llm
)

result = adv_rag.query(
    "what is attention mechanism",
    top_k=3,
    min_score=0.1,
    stream=True,
    summarize=True
)

print("\nFinal Answer:", result["answer"])
print("Summary:", result["summary"])
print("History:", result["history"][-1])

Retrieving documents for query: 'what is attention mechanism'
Top K: 3, Score threshold: 0.1
Generating embeddings for 1 texts...

Batches: 100%|██████████| 1/1 [00:00<00:00, 62.36it/s]

Generated embeddings with shape: (1, 384)
Retrieved 3 documents (after filtering)
Streaming answer:
Use the following context to answer the question concisely.
Context:
(see Table A.4 for a complete reference).
Definition 2.1(Attention Mechanism).An attention mechanism is a differentiable functionA:R dq×
Rn×dk×Rn×dv→R dv that computes a weighted combination of values based on the compatibility between
a query and key

s.
Given:
•Query:q∈R dq
•Keys:K= (k 1,...,k n) wherek i∈R dk
•Values:V= (v 1,...,v n) wherev i∈R dv
The attention function computes:
ei = score(q,ki) fori= 1,...,n(2.8)
αi = exp(ei)Pn
j=1 exp(ej) (2.9)
A(q,K,V) =
nX
i=1
αivi (2.10)
where score :Rdq×Rdk→Ris a compatibility function, andα i are attention weights satisfyingPn
i=1αi =
1 andα i≥0.
The attention mechanism consists of three conceptual stages:
Stage 1 - Score Computation: For each positioni, compute a scalar scoree i measuring the com-
patibility or relevance between the queryqand keyk i. Different scoring functions are explored in the next
section.

18 CHAPTER 3. SELF-ATTENTION MECHANISMS
Example 3.2(Positional Patterns).Some attention heads learn to attend to specific relative positions.
For instance, a head might attend primarily to the next position (A i,i+1 ≈1) or the previous position
(Ai,i−1≈1). These patterns extract positional information.
Example 3.3(Syntactic Patterns).In language models, certain heads learn attention patterns that follow
syntactic structure. For example:
•Heads that attend from verbs to their subjects
•Heads that attend from pronouns to their antecedents
•Heads that attend from words to their modifiers
These patterns emerge without explicit syntactic supervision, suggesting that attention mechanisms
discover grammatical structure through language modeling objectives.
Example 3.4(Broadcast Patterns).Some heads develop attention patterns where certain positions (often
the first position or special tokens) receive attention from most other positions. These positions act as

constraints.
2.Efficiency: Computation should be parallelizable across positions to leverage modern hardware.
3.Adaptivity: The patterns of information flow should be learned from data rather than hardcoded.
4.Bounded Memory: Memory requirements should not grow excessively with sequence length.
5.Long-Range Modeling: The mechanism should effectively capture dependencies between distant po-
sitions.
Attention mechanisms satisfy most of these desiderata, though the memory requirement grows quadrat-
ically with sequence length in the standard formulation.
2.3 The General Attention Function
We now formally define the attention mechanism that forms the foundation for all subsequent developments.
The notation introduced here for queries, keys, and values is used consistently throughout the monograph
(see Table A.4 for a complete reference).
Definition 2.1(Attention Mechanism).An attention mechanism is a differentiable functionA:R dq×

Question: what is attention mechanism

Answer:

Final Answer: An attention mechanism is a differentiable function that, given a query vector q, a set of key vectors K, and a set of value vectors V, computes a weighted sum of the values. The weights are derived from a compatibility score between the query and each key, normalized with a softmax. Formally:

1. Compute scores \(e_i = \text{score}(q, k_i)\) for each key \(k_i\).
2. Convert scores to attention weights \(\alpha_i = \frac{\exp(e_i)}{\sum_j \exp(e_j)}\).
3. Produce the output \(A(q,K,V) = \sum_i \alpha_i v_i\).

The mechanism learns how to focus on relevant positions in the input, enabling efficient, adaptive, and parallelizable information flow.

Citations:
[1] Attention.pdf (page 10)
[2] Attention.pdf (page 19)
[3] Attention.pdf (page 10)
Summary: An attention mechanism is a differentiable function that takes a query vector, a set of key vectors, and a set of value vectors, computes a compatibility score for each key, normalizes these scores with a softmax to obtain attention weights, and then produces a weighted sum of the values. This process allows the model to learn where to focus in the input, enabling efficient, adaptive, and parallelizable information flow.
History: {'question': 'what is attention mechanism', 'answer': 'An attention mechanism is a differentiable function that, given a query vector\u202fq, a set of key vectors\u202fK, and a set of value vectors\u202fV, computes a weighted sum of the values. The weights are derived from a compatibility score between the query and each key, normalized with a softmax. Formally:\n\n1. Compute scores \\(e_i = \\text{score}(q, k_i)\\) for each key \\(k_i\\).\n2. Convert scores to attention weights \\(\\alpha_i = \\frac{\\exp(e_i)}{\\sum_j \\exp(e_j)}\\).\n3. Produce the output \\(A(q,K,V) = \\sum_i \\alpha_i v_i\\).\n\nThe mechanism learns how to focus on relevant positions in the input, enabling efficient, adaptive, and parallelizable information flow.', 'sources': [{'source': 'Attention.pdf', 'page': 10, 'score': 0.3388022184371948, 'preview': '(see Table A.4 for a complete reference).\nDefinition 2.1(Attention Mechanism).An attention mechanism is a differentiable...'}, {'source': 'Attention.pdf', 'page': 19, 'score': 0.3105357885360718, 'preview': '18 CHAPTER 3. SELF-ATTENTION MECHANISMS\nExample 3.2(Positional Patterns).Some attention heads learn to attend to specifi...'}, {'source': 'Attention.pdf', 'page': 10, 'score': 0.27148711681365967, 'preview': 'constraints.\n2.Efficiency: Computation should be parallelizable across positions to leverage modern hardware.\n3.Adaptivi...'}], 'summary': 'An attention mechanism is a differentiable function that takes a query vector, a set of key vectors, and a set of value vectors, computes a compatibility score for each key, normalizes these scores with a softmax to obtain attention weights, and then produces a weighted sum of the values. This process allows the model to learn where to focus in the input, enabling efficient, adaptive, and parallelizable information flow.'}

In [23]:
# Example usage
adv_rag = AdvancedRAGPipeline(
    rag_retriever,
    llm
)

result = adv_rag.query(
    "what is CNN?",
    top_k=3,
    min_score=0.1,
    stream=True,
    summarize=True
)

print("\nFinal Answer:", result["answer"])
print("Summary:", result["summary"])
print("History:", result["history"][-1])

Retrieving documents for query: 'what is CNN?'
Top K: 3, Score threshold: 0.1
Generating embeddings for 1 texts...

Batches: 100%|██████████| 1/1 [00:00<00:00, 46.48it/s]

Generated embeddings with shape: (1, 384)
Retrieved 3 documents (after filtering)
Streaming answer:
Use the following context to answer the question concisely.
Context:
Electronics 2021, 10, 2470 2 of 28
computer vision algorithms. A convolutional neural network is a method of deep learning
that takes an input image and assigns importance (learnable biases and weights) to various
objects in the image, distinguishing

one from the other [1].
In comparison to other methods, CNN requires less preprocessing. Therefore, a CNN
is the most effective learning algorithm for comprehending picture material [1]. Further-
more, it has demonstrated exceptional image classiﬁcation, recognition, segmentation, and
retrieval [2]. The accomplishment of CNN has piqued the interest of people outside of
academia. Microsoft, Google, AT&T, NEC, and Facebook are among the companies engag-
ing in the development and advancement of CNN architecture [3]. In addition, they have
active research groups that are investigating novel CNN designs. At the moment, deep
CNN-based models are being used by the majority of front-runners in image processing

(Smarandache et al., 2019) reviewed trends in convolutional neural network architecture.
This paper primarily focuses on the design of the architecture of around 10 well-known
CNN models.
Similarly, there are many authors, such as Liu (2017), LeCun (2010), Guo (2016), and
Srinivas (2016), who have discussed CNN’s many applications and tactics [4,6–8]. As a
result, this survey exempliﬁes the essential taxonomy discovered in the most recent and
well-known CNN designs reported between 2012 and 2021. This manuscript includes

of AlexNet in 2012 opened the door for computer vision applications, and many various
forms of CNNs, such as the R-CNN series, have been raised. CNN models now are quite
different from LeNet, although they are all based on it.
In recent years, several exciting survey papers have been published on deep CNN. For
example, (Asifullah Khan et al., 2018) examined prominent structures from 2012 to 2018 and
their major components. (Alzubaidi et al., 2021) reviewed deep learning concepts, CNN
architecture, challenges, and future trends. This paper was the ﬁrst paper to include various
DL aspects. It also includes the impact of CPU, GPU, and FPGA on various deep learning
approaches. It includes one section about the introduction to CNN and its architecture.
(Smarandache et al., 2019) reviewed trends in convolutional neural network architecture.
This paper primarily focuses on the design of the architecture of around 10 well-known
CNN models.

Question: what is CNN?

Answer:

Final Answer: A Convolutional Neural Network (CNN) is a deep‑learning architecture that processes images by applying convolutional layers to learn spatial hierarchies of features. It automatically assigns importance (weights and biases) to different parts of an image, enabling tasks such as classification, recognition, segmentation, and retrieval with minimal preprocessing.

Citations:
[1] CNN.pdf (page 1)
[2] CNN.pdf (page 1)
[3] CNN.pdf (page 1)
Summary: A CNN is a deep‑learning model that uses convolutional layers to learn spatial hierarchies of image features, automatically weighting different regions through learned weights and biases. This enables it to perform tasks such as classification, recognition, segmentation, and retrieval with minimal preprocessing.
History: {'question': 'what is CNN?', 'answer': 'A Convolutional Neural Network (CNN) is a deep‑learning architecture that processes images by applying convolutional layers to learn spatial hierarchies of features. It automatically assigns importance (weights and biases) to different parts of an image, enabling tasks such as classification, recognition, segmentation, and retrieval with minimal preprocessing.', 'sources': [{'source': 'CNN.pdf', 'page': 1, 'score': 0.23530572652816772, 'preview': 'Electronics 2021, 10, 2470 2 of 28\ncomputer vision algorithms. A convolutional neural network is a method of deep learni...'}, {'source': 'CNN.pdf', 'page': 1, 'score': 0.23018181324005127, 'preview': '(Smarandache et al., 2019) reviewed trends in convolutional neural network architecture.\nThis paper primarily focuses on...'}, {'source': 'CNN.pdf', 'page': 1, 'score': 0.16169840097427368, 'preview': 'of AlexNet in 2012 opened the door for computer vision applications, and many various\nforms of CNNs, such as the R-CNN s...'}], 'summary': 'A CNN is a deep‑learning model that uses convolutional layers to learn spatial hierarchies of image features, automatically weighting different regions through learned weights and biases. This enables it to perform tasks such as classification, recognition, segmentation, and retrieval with minimal preprocessing.'}

### RAG Evaluation

We evaluate the pipeline in two layers:

**1. Retrieval quality** (is the right context being fetched?)
- **Hit Rate@k** - did at least one relevant chunk appear in the top-k?
- **MRR** - how high is the first relevant chunk ranked?
- **Precision@k** - what fraction of the top-k chunks are relevant?
- **Keyword Coverage** - what fraction of the expected key facts/terms appear in the retrieved context (a cheap proxy for context recall)

**2. Generation quality** (is the answer good, given the context?)
- **Faithfulness** (LLM-as-judge) - is every claim in the answer supported by the retrieved context? (hallucination check)
- **Answer Relevancy** (LLM-as-judge) - does the answer actually address the question?
- **Answer Similarity** - cosine similarity between the generated answer and a reference answer (embedding based)

A chunk counts as *relevant* if it comes from the expected PDF **and** contains at least one expected keyword.

In [24]:
# --- Evaluation dataset ---
# Edit / extend this with your own questions. Aim for 15-30 for stable numbers.
# expected_source : PDF file name that should be retrieved
# keywords        : terms that a relevant chunk should contain (case-insensitive)
# reference       : short ground-truth answer (used for Answer Similarity)

eval_dataset = [
    {
        "question": "What is the attention mechanism?",
        "expected_source": "Attention.pdf",
        "keywords": ["attention mechanism", "query", "keys", "values"],
        "reference": "An attention mechanism is a differentiable function that computes a weighted combination of values based on the compatibility between a query and keys."
    },
    {
        "question": "What is a convolutional neural network?",
        "expected_source": "CNN.pdf",
        "keywords": ["convolutional neural network", "input image", "deep learning"],
        "reference": "A CNN is a deep learning method that takes an input image and assigns learnable weights and biases to objects in the image to distinguish one from another."
    },
    {
        "question": "What is SadakVision?",
        "expected_source": "SadakVision \u2014 INDIS 2026.pdf",
        "keywords": ["sadakvision", "sensor", "vision"],
        "reference": "SadakVision is a sensor-and-vision fusion system where the sensor decides when the camera looks, and the vision model gives the verdict."
    },
    {
        "question": "How much compute does SadakVision save compared to vision-only?",
        "expected_source": "SadakVision \u2014 INDIS 2026.pdf",
        "keywords": ["89%", "frames", "4,620", "43,200"],
        "reference": "SadakVision uses about 89% less compute, sending 4,620 frames to the detector per hour versus 43,200."
    },
    {
        "question": "What did the randomized controlled trial find about teaching children to read in India?",
        "expected_source": "A better way to teach children to read in India.pdf",
        "keywords": ["randomized", "reading", "children", "Shishu"],
        "reference": "The randomized controlled trial evaluated a new method of teaching children to read in India (the Shishu program)."
    },
]
print(f"{len(eval_dataset)} eval questions loaded")

5 eval questions loaded

#### Retrieval metrics

In [25]:
import io, contextlib
import numpy as np

def is_relevant(doc, item):
    """A retrieved chunk is relevant if it's from the expected PDF and has >=1 expected keyword."""
    src = doc["metadata"].get("source_file", doc["metadata"].get("source", ""))
    if item["expected_source"].lower() not in src.lower():
        return False
    text = doc["content"].lower()
    return any(k.lower() in text for k in item["keywords"])


def dedupe(docs):
    """The vector store may contain duplicate chunks (see note below) - keep the first of each."""
    seen, out = set(), []
    for d in docs:
        key = d["content"].strip()
        if key not in seen:
            seen.add(key)
            out.append(d)
    return out


def evaluate_retrieval(dataset, retriever, k=5, dedupe_results=True):
    rows = []
    for item in dataset:
        # silence the retriever's verbose prints, fetch extra so dedupe can still fill k
        with contextlib.redirect_stdout(io.StringIO()):
            docs = retriever.retrieve(item["question"], top_k=k * 3 if dedupe_results else k)
        if dedupe_results:
            docs = dedupe(docs)
        docs = docs[:k]

        rel_flags = [is_relevant(d, item) for d in docs]
        first_rel = next((i for i, f in enumerate(rel_flags) if f), None)

        context = " ".join(d["content"].lower() for d in docs)
        kw_cov = np.mean([kw.lower() in context for kw in item["keywords"]])

        rows.append({
            "question": item["question"],
            "hit": float(any(rel_flags)),
            "mrr": 1.0 / (first_rel + 1) if first_rel is not None else 0.0,
            "precision": sum(rel_flags) / max(len(docs), 1),
            "keyword_coverage": float(kw_cov),
        })
    return rows

In [26]:
import pandas as pd

K = 5
retrieval_rows = evaluate_retrieval(eval_dataset, rag_retriever, k=K)
retrieval_df = pd.DataFrame(retrieval_rows)

display(retrieval_df.round(3))
print(f"\n===== Retrieval metrics (k={K}) =====")
print(f"Hit Rate@{K}       : {retrieval_df['hit'].mean():.3f}")
print(f"MRR               : {retrieval_df['mrr'].mean():.3f}")
print(f"Precision@{K}      : {retrieval_df['precision'].mean():.3f}")
print(f"Keyword Coverage  : {retrieval_df['keyword_coverage'].mean():.3f}")

Batches: 100%|██████████| 1/1 [00:00<00:00, 33.23it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 53.16it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 46.23it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 59.99it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 53.26it/s]

,question,hit,mrr,precision,keyword_coverage
0,What is the attention mechanism?,1.0,1.0,0.6,1.000
1,What is a convolutional neural network?,1.0,1.0,0.8,1.000
2,What is SadakVision?,0.0,0.0,0.0,0.667
3,How much compute does SadakVision save compare...,1.0,1.0,0.5,1.000
4,What did the randomized controlled trial find ...,1.0,1.0,1.0,1.000

===== Retrieval metrics (k=5) =====
Hit Rate@5       : 0.800
MRR               : 0.800
Precision@5      : 0.580
Keyword Coverage  : 0.933

#### Generation metrics (LLM-as-judge + embedding similarity)

In [27]:
import json, re, time

def run_rag(question, retriever, llm, top_k=5):
    """Run the pipeline and return answer + the exact context the LLM saw."""
    with contextlib.redirect_stdout(io.StringIO()):
        docs = dedupe(retriever.retrieve(question, top_k=top_k * 3))[:top_k]
    if not docs:
        return {"answer": "No relevant context found.", "context": ""}
    context = "\n\n".join(d["content"] for d in docs)
    prompt = f"""Use the following context to answer the question concisely.
Only use information from the provided context.

Context:
{context}

Question: {question}

Answer:"""
    return {"answer": llm.invoke(prompt).content, "context": context}


def _parse_json(text):
    """Pull the first JSON object out of an LLM response."""
    m = re.search(r"\{.*\}", text, re.DOTALL)
    return json.loads(m.group(0)) if m else {}


def judge_faithfulness(question, answer, context, llm):
    """Score 0-1: share of the answer's claims that are supported by the context."""
    prompt = f"""You are a strict evaluator. Break the ANSWER into individual factual claims, then
check each claim against the CONTEXT only (ignore your own knowledge).

CONTEXT:
{context}

ANSWER:
{answer}

Return ONLY JSON: {{"total_claims": <int>, "supported_claims": <int>, "reason": "<one sentence>"}}"""
    out = _parse_json(llm.invoke(prompt).content)
    total = out.get("total_claims", 0)
    return (out.get("supported_claims", 0) / total) if total else 0.0


def judge_answer_relevancy(question, answer, llm):
    """Score 0-1: does the answer directly address the question?"""
    prompt = f"""Rate how well the ANSWER addresses the QUESTION on a scale from 0 to 5
(0 = irrelevant / refuses, 3 = partially answers, 5 = fully and directly answers).
Do not judge factual correctness, only relevance and completeness.

QUESTION: {question}
ANSWER: {answer}

Return ONLY JSON: {{"score": <0-5>, "reason": "<one sentence>"}}"""
    out = _parse_json(llm.invoke(prompt).content)
    return float(out.get("score", 0)) / 5.0


def answer_similarity(answer, reference, embedding_manager):
    """Cosine similarity between generated answer and reference answer."""
    vecs = embedding_manager.model.encode([answer, reference], convert_to_numpy=True)
    return float(cosine_similarity([vecs[0]], [vecs[1]])[0][0])

In [28]:
def evaluate_generation(dataset, retriever, llm, embedding_manager, top_k=5, sleep_s=1.0):
    rows = []
    for item in dataset:
        try:
            res = run_rag(item["question"], retriever, llm, top_k=top_k)
            faith = judge_faithfulness(item["question"], res["answer"], res["context"], llm)
            relev = judge_answer_relevancy(item["question"], res["answer"], llm)
            sim = (answer_similarity(res["answer"], item["reference"], embedding_manager)
                   if item.get("reference") else np.nan)
            rows.append({
                "question": item["question"],
                "faithfulness": faith,
                "answer_relevancy": relev,
                "answer_similarity": sim,
                "answer": res["answer"],
            })
        except Exception as e:  # e.g. rate limit / bad JSON - keep going
            print(f"Skipped '{item['question']}': {e}")
        time.sleep(sleep_s)  # be gentle with Groq rate limits
    return rows

In [29]:
generation_rows = evaluate_generation(eval_dataset, rag_retriever, llm, embedding_manager, top_k=5)
generation_df = pd.DataFrame(generation_rows)

display(generation_df.drop(columns=["answer"]).round(3))
print("\n===== Generation metrics =====")
print(f"Faithfulness      : {generation_df['faithfulness'].mean():.3f}")
print(f"Answer Relevancy  : {generation_df['answer_relevancy'].mean():.3f}")
print(f"Answer Similarity : {generation_df['answer_similarity'].mean():.3f}")

Batches: 100%|██████████| 1/1 [00:00<00:00, 52.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 74.62it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 75.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 63.13it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 29.65it/s]

,question,faithfulness,answer_relevancy,answer_similarity
0,What is the attention mechanism?,1.0,1.0,0.889
1,What is a convolutional neural network?,1.0,0.6,0.864
2,What is SadakVision?,1.0,1.0,0.758
3,How much compute does SadakVision save compare...,1.0,1.0,0.733
4,What did the randomized controlled trial find ...,0.0,1.0,0.776

===== Generation metrics =====
Faithfulness      : 0.800
Answer Relevancy  : 0.920
Answer Similarity : 0.804

#### Summary report

In [30]:
summary = pd.Series({
    f"Hit Rate@{K}": retrieval_df["hit"].mean(),
    "MRR": retrieval_df["mrr"].mean(),
    f"Precision@{K}": retrieval_df["precision"].mean(),
    "Keyword Coverage": retrieval_df["keyword_coverage"].mean(),
    "Faithfulness": generation_df["faithfulness"].mean(),
    "Answer Relevancy": generation_df["answer_relevancy"].mean(),
    "Answer Similarity": generation_df["answer_similarity"].mean(),
}, name="score").round(3)

display(summary.to_frame())

# Optional: save per-question results so you can compare runs after changing
# chunk_size, embedding model, top_k, prompt, etc.
retrieval_df.merge(generation_df.drop(columns=["answer"]), on="question").to_csv("../data/eval_results.csv", index=False)

                   score
Hit Rate@5         0.800
MRR                0.800
Precision@5        0.580
Keyword Coverage   0.933
Faithfulness       0.800
Answer Relevancy   0.920
Answer Similarity  0.804

> **Note on duplicate chunks:** the earlier output shows the collection holding **2,275** documents although this PDF set only produces **440** chunks - the ingestion cell was run several times and `add_documents` generates a new random ID each run, so the same chunk is stored multiple times. Duplicates crowd the top-k with copies of one chunk and distort retrieval metrics. The eval above de-duplicates results to compensate, but the proper fix is to delete and re-create the collection (or use deterministic IDs, e.g. a hash of the chunk text, with `collection.upsert`).